### PR TITLE
feat: Make common package to include key and amount

### LINKED ISSUE #18: Create branches specific to the SDK for each contract model.
## Expected Behavior
- The SDK for each contract model is implemented on a different branch.
- The SDK for each contract model includes only the necessary common libraries(alias, base, key, utils) and contract-specific operations.
- The amount.js is excluded from currency operation folder and is included in the common library folder.
- Each SDK is published to the npm registry with a unique library name.
- A developer should selectively install each SDK library.
## Actual Behavior
- The SDK for each contract model is implemented on a different repository.

### PR DESCRIPTION
**Pull request by soonkuk**
### Pull-request Type (fix, feat, bug, doc, chore, test, etc...) 
- feat
### Current Behavior (Link to an open issue)
- close #18 
### New Behavior (if this is a feature change)
- The amount file moves to the common package
- The key package moves to the common package

### CODE REVIEW

**Comment by wyuinche** [comment]
@soonkuk Is this PR a preprocessing for integrating sdk from other models such as feefi into this sdk?

**Comment by soonkuk** [comment]
> @soonkuk Is this PR a preprocessing for integrating sdk from other models such as feefi into this sdk?
Yes, that's right.

**Review by wyuinche — COMMENTED** [review]
In my opinion, the folder called `common` is not essential because there are not many other codes required other than `operations` and the distinction is already clear. If `amount.js` is common to all models, it looks better under the `operations` folder.

**Comment by soonkuk** [comment]
@wyuinche Ok I got it. The reason why I thought the amount.js file should be in the common package is that an Amount type was used out of currency package. But I have realized that it will be resolved if a SDK module for the other contract model imports an Amount type from the mitum-currency-SDK. So I will close this PR.

**Pull request closed without merging**
